- name: install packages
  apt: pkg={{ item }}
  with_items:
    - postgresql-9.1
    - postgresql-9.1-postgis
    - postgresql-contrib-9.1
    - openjdk-6-jre-headless  # for osmosis

    # for osm2pgsql compilation
    - libboost-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-thread-dev
    - libxml2-dev
    - libgeos-dev
    - libgeos++-dev
    - libpq-dev
    - libbz2-dev
    - libproj-dev
    - protobuf-c-compiler
    - libprotobuf-c0-dev
    - lua5.2
    - liblua5.2-dev
    - autoconf
    - automake
    - libtool
    - make
    - g++

- name: ensure postgresql server is running
  service: name=postgresql state=started

- include: ../../../shared/project-account.yml user=osm2pgsql

- name: add sudoers to access osm2pgsql user
  copy: src=sudoers dest=/etc/sudoers.d/osm2pgsql-backend mode=0440 owner=root group=root validate='visudo -cf %s'

- name: init database
  postgresql_db: name=osm encoding='UTF-8' lc_collate='fr_FR.UTF-8' lc_ctype='fr_FR.UTF-8' template='template0'
  register: createdb_osm
  sudo: yes
  sudo_user: postgres

- name: init database user
  postgresql_user: name=osm2pgsql password=WejOInL3FT db=osm priv=ALL
  sudo: yes
  sudo_user: postgres

- name: psql extension hstore
  command: psql -d osm -c "CREATE EXTENSION IF NOT EXISTS {{ item }}"
  register: psql_res
  changed_when: "not 'extension \"{{ item }}\" already exists' in '{{ psql_res.stderr }}'"
  sudo: yes
  sudo_user: postgres
  with_items:
    - fuzzystrmatch
    - hstore

- name: psql extension postgis
  command: psql -d osm -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql
  when: createdb_osm.changed
  sudo: yes
  sudo_user: postgres

- name: psql extension postgis - spatial_ref_sys
  command: psql -d osm -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql
  when: createdb_osm.changed
  sudo: yes
  sudo_user: postgres

- name: psql access to tables
  postgresql_privs: database=osm type=table objs={{ item }} roles=osm2pgsql privs=SELECT,INSERT,UPDATE,DELETE
  sudo: yes
  sudo_user: postgres
  with_items:
    - geometry_columns
    - spatial_ref_sys


- name: psql check schema osm2pgsql
  command: psql -t -d osm -c "SELECT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'osm2pgsql');"
  register: check_schema
  changed_when: "'f' in '{{ check_schema.stdout }}'"
  sudo: yes
  sudo_user: postgres

- name: psql schema osm2pgsql
  command: psql -d osm -c "CREATE SCHEMA osm2pgsql; ALTER USER osm2pgsql SET search_path TO osm2pgsql, public;"
  when: check_schema.changed
  sudo: yes
  sudo_user: osm2pgsql

- name: psql grant access to schema osm2pgsql to all
  postgresql_privs: database=osm type=schema objs=osm2pgsql roles=PUBLIC privs=USAGE
  sudo: yes
  sudo_user: postgres

- name: psql grant acces to tables of schema osm2pgsql
  postgresql_privs: database=osm schema=osm2pgsql type=table objs=ALL_IN_SCHEMA roles=PUBLIC privs=SELECT
  sudo: yes
  sudo_user: postgres

- name: checkout git repository
  git: repo=https://github.com/openstreetmap/osm2pgsql.git dest=/data/project/osm2pgsql/osm2pgsql/ force=no update=no
  sudo: yes
  sudo_user: osm2pgsql

- name: compile osm2pgsql
  shell: chdir=/data/project/osm2pgsql/osm2pgsql/ ./autogen.sh && ./configure && make
  register: make
  sudo: yes
  sudo_user: osm2pgsql

- name: checkout git repository
  git: repo=https://github.com/osm-fr/osm2pgsql-import-tools.git dest=/data/project/osm2pgsql/import-base-osm force=no update=no
  sudo: yes
  sudo_user: osm2pgsql

- name: download osmosis
  get_url: url=http://bretth.dev.openstreetmap.org/osmosis-build/osmosis-0.43.1.tgz dest=/data/project/osm2pgsql/osmosis-0.43.1.tgz sha256sum=68df488db3643499cbc3d56fd4bd8bcabb9d67e821f9ba365b7e2eed6bda426a
  sudo: yes
  sudo_user: osm2pgsql

- include: ../../../shared/osmosis.yml user=osm2pgsql version=0.43.1

- name: add munin plugin
  file: src="/data/project/osm2pgsql/import-base-osm/maintenance/munin/osm_replication_lag-osm2pgsql" dest="/etc/munin/plugins/osm_replication_lag-osm2pgsql" state=link

- name: add munin plugin conf
  file: src="/data/project/osm2pgsql/import-base-osm/maintenance/munin/osm_replication_lag-osm2pgsql.conf" dest="/etc/munin/plugin-conf.d/osm_replication_lag-osm2pgsql" state=link

# To finish installation, run:
# - (cd /data/work/osm2pgsql/ && wget http://download.openstreetmap.fr/extracts/europe/france.osm.pbf)
# - (cd import-base-osm && ./import.sh /data/work/osm2pgsql/france.osm.pbf)
