- name: check ansible version
  assert:
    that:
      - "ansible_version.full | version_compare('2.3', '>=')"
    msg: "ansible version must be >= 2.3, please update ansible."

- include: ../../../shared/project-account.yml user="{{ overpass_user }}" user_system="yes"


- name: set overpass_database_dir
  set_fact:
    overpass_database_dir: "{{ ssd_dir|default(work_dir) }}/database"

- name: set overpass_webroot_dir
  set_fact:
    overpass_webroot_dir: "{{ work_dir }}/www"

- name: create overpass_database_dir and overpass_webroot_dir
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ overpass_user }}"
    group: "{{ overpass_user }}"
  with_items:
    - "{{ overpass_database_dir }}"
    - "{{ overpass_webroot_dir }}"

- include: compile.yml
- include: set_up_database.yml
- include: services.yml
- include: web.yml
- include: munin.yml
- include: restart.yml
