---
- name: test if /etc/munin/plugins exists
  stat:
    path: /etc/munin/plugins
  register: stat_result

- name: install munin plugins
  template:
    src: templates/munin/overpass_db_lag
    dest: /etc/munin/plugins
    mode: 0755
  notify:
    - restart munin-node
  when:
    - stat_result.stat.exists == True
