- name: install packages
  apt:
    pkg: "{{ item }}"
  with_items:
    - nginx
    - fcgiwrap

- name: configure api endpoint
  template:
    src: templates/default.conf
    dest: /etc/nginx/sites-available/default

- name: install html page
  template:
    src: "templates/{{ item }}"
    dest: "{{ overpass_webroot_dir }}"
  with_items:
    - index.html
    - api.html

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
