- name: reload opendkim-verifier
  systemd: name=opendkim-verifier state=reloaded

- name: reload opendkim-signer
  systemd: name=opendkim-signer state=reloaded

- name: reload opendmarc
  systemd: name=opendmarc state=reloaded

- name: reload postfix
  systemd: name=postfix state=reloaded


- name: restart opendkim-verifier
  systemd: name=opendkim-verifier state=restarted

- name: restart opendkim-signer
  systemd: name=opendkim-signer state=restarted
