- name: install unattended-upgrades
  apt: pkg=unattended-upgrades state=present

- name: create APT auto-upgrades configuration
  copy: >
    src=auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades
    owner=root group=root mode=0644
