- name: install packages
  apt: pkg={{ item }}
  with_items:
    - openjdk-6-jre-headless

- include: ../../../shared/project-account.yml user=jenkins

- name: add sudoers to access osmose user
  copy: src=sudoers dest=/etc/sudoers.d/jenkins-slave mode=0440 owner=root group=root validate='visudo -cf %s'

- name: init ssh key to jenkins user
  authorized_key: user=jenkins key="{{ item }}"
  with_file:
    - jenkins-ssh-key

- name: init /data/work/jenkins/ sub path
  file: path=/data/work/jenkins/{{ item }} state=directory owner=jenkins group=jenkins
  with_items:
    - tmp
