- include: ../../../shared/project-account.yml user=osmbin

- name: add sudoers to access osmbin user
  copy: src=sudoers dest=/etc/sudoers.d/osmbin mode=0440 owner=root group=root validate='visudo -cf %s'

- name: checkout git repository
  git: repo=https://github.com/jocelynj/osm.git dest=/data/project/osmbin/osm force=no update=no
  sudo: yes
  sudo_user: osmbin
