- name: install packages
  apt: pkg={{ item }}
  with_items:
    - python-lockfile
    - python-imposm

- include: ../../../shared/project-account.yml user=osmbin

- name: add sudoers to access osmbin user
  copy: src=sudoers dest=/etc/sudoers.d/osmbin mode=0440 owner=root group=root validate='visudo -cf %s'

- name: checkout git repository
  git: repo=https://github.com/jocelynj/osm.git dest=/data/project/osmbin/osm force=no update=no
  sudo: yes
  sudo_user: osmbin

- name: init OsmBin
  command: chdir=/data/project/osmbin/osm/osc_modif/modules
           creates=/data/work/osmbin/data/node.crd
           ./OsmBin.py --init /data/work/osmbin/data
  sudo: yes
  sudo_user: osmbin
