- name: init osmbin user
  user: name=osmbin home=/data/project/osmbin/ shell=/bin/bash

- name: init /data/work/osmbin path
  file: path=/data/work/osmbin state=directory owner=osmbin group=osmbin

- name: add sudoers to access osmbin user
  copy: src=sudoers dest=/etc/sudoers.d/osmbin mode=0440 owner=root group=root validate='visudo -cf %s'

- name: checkout git repository
  git: repo=https://github.com/jocelynj/osm.git dest=/data/project/osmbin/osm force=no update=no
  sudo: yes
  sudo_user: osmbin
