- name: install packages
  apt: pkg={{ item }}
  with_items:
    - buildbot-slave

- name: init paths
  file: path={{ item }} state=directory owner=buildbot group=buildbot force=no
  with_items:
    - /data/work/buildbot-slave

- name: add sudoers to access osmose user
  copy: src=sudoers dest=/etc/sudoers.d/buildbot-slave mode=0440 owner=root group=root validate='visudo -cf %s'

- name: configure buildbot directory
  sudo: yes
  sudo_user: buildbot
  command:
    creates="/data/work/buildbot-slave/buildbot.tac" chdir="/data/work/buildbot-slave/"
    /usr/bin/buildslave create-slave . buildbot.osmose.openstreetmap.fr:8127 {{ inventory_hostname.split(".") | first }} "{{ lookup('password', 'credentials/' + inventory_hostname + '/buildbot-slave-password length=15 chars=ascii_letters,digits') }}"

- name: enable buildslave
  lineinfile: dest=/etc/default/buildslave regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items:
    - {regexp: "SLAVE_ENABLED.1.=",   line: "SLAVE_ENABLED[1]=1"}
    - {regexp: "SLAVE_NAME.1.=",      line: 'SLAVE_NAME[1]=\"buildslave #1\"'}
    - {regexp: "SLAVE_USER.1.=",      line: 'SLAVE_USER[1]=\"buildbot\"'}
    - {regexp: "SLAVE_BASEDIR.1.=",   line: 'SLAVE_BASEDIR[1]=\"/data/work/buildbot-slave\"'}
    - {regexp: "SLAVE_OPTIONS.1.=",   line: 'SLAVE_OPTIONS[1]=\"\"'}
    - {regexp: "SLAVE_PREFIXCMD.1.=", line: 'SLAVE_PREFIXCMD[1]=\"\"'}
  notify: restart buildslave
