- name: check if apache installed
  command: /usr/bin/test -e /etc/apache2/conf-available/ -a -e /etc/apache2/conf-enabled/
  ignore_errors: True
  register: apache_installed

# change logformat from %h to %a to support reverse proxy
- name: configure logformat for apache
  copy:
    src: "apache-logformat.conf"
    dest: "/etc/apache2/conf-available/ansible-logformat.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload apache
  when: apache_installed.rc == 0

- name: enable logformat config for apache
  file:
    src:  /etc/apache2/conf-available/ansible-logformat.conf
    dest: /etc/apache2/conf-enabled/ansible-logformat.conf
    state: link
  notify: reload apache
  when: apache_installed.rc == 0

# enable mod_remoteip for reverse proxy
- name: configure remoteip
  template:
    src: apache-remoteip.conf
    dest: /etc/apache2/mods-available/remoteip.conf
    mode: 0644
    owner: root
    group: root
  notify: reload apache
  when: apache_installed.rc == 0 and vm_host is defined

- name: enable mod_remoteip
  file:
    src:  "/etc/apache2/mods-available/{{ item }}"
    dest: "/etc/apache2/mods-enabled/{{ item }}"
    state: link
  notify: restart apache
  with_items:
    - remoteip.load
    - remoteip.conf
  when: apache_installed.rc == 0 and vm_host is defined
