- name: bootstrap python-apt package
  raw: apt-get -y install python-apt

#- apt: update_cache=yes
- name: install packages
  apt: pkg={{ item }}
  with_items:
    - python
    - python-apt

    - atop
    - bash-completion
    - etckeeper
    - git
    - htop
    - lftp
    - libdbd-pg-perl  # for postgresql's munin plugin
    - libwww-perl  # for apache's munin plugin
    - monit
    - munin-node
    - sudo
    - vim-nox

- name: install sensors package
  apt: pkg={{ item }}
  with_items:
    - lm-sensors   # for sensors's munin plugin
  notify:
    - detect sensors

- include: ../../../shared/account.yml user=cquest  uid=1202
- include: ../../../shared/account.yml user=jocelyn uid=1203

- name: add default sudoers
  copy: src=sudoers dest=/etc/sudoers.d/ansible-common mode=0440 owner=root group=root validate='visudo -cf %s'

- name: configure locales
  lineinfile: dest=/etc/locale.gen regexp="{{ item }}" line="{{ item }} "
  notify:
    - generate locales
  with_items:
    - en_GB.UTF-8 UTF-8
    - en_US.UTF-8 UTF-8
    - fr_FR.UTF-8 UTF-8

- include: munin-node.yml

- include: ntp.yml
  when: "not 'vm' in {{ group_names }}"
