- name: add allowed hosts to munin-node
  lineinfile: dest=/etc/munin/munin-node.conf regexp="^allow .{{ item.regexp }}.$"
              insertafter="^allow" line="allow ^{{ item.ip }}$"
  notify:
    - restart munin-node
  with_items:
    - {ip: '138\.231\.138\.102', regexp: "138..231..138..102"}
    - {ip: "2a01:240:fe3d:4:214:c2ff:fe3f:9e5c", regexp: "2a01:240:fe3d:4:214:c2ff:fe3f:9e5c"}

- name: configure hostname of munin-node
  lineinfile: dest=/etc/munin/munin-node.conf regexp="^host_name {{ inventory_hostname }}"
              insertafter="^#host_name" line="host_name {{ inventory_hostname  }}"
  notify:
    - restart munin-node

- name: add plugin links
  file: state=link src="{{ item.src }}" dest="/etc/munin/plugins/{{ item.dest }}" force=no
  notify:
    - restart munin-node
  with_items:
    - {src: /usr/share/munin/plugins/apache_accesses, dest: apache_accesses}
    - {src: /usr/share/munin/plugins/apache_processes, dest: apache_processes}
    - {src: /usr/share/munin/plugins/apache_volume, dest: apache_volume}
    - {src: /usr/share/munin/plugins/df_abs, dest: df_abs}

- name: add plugin links for sensors
  file: state=link src="{{ item.src }}" dest="/etc/munin/plugins/{{ item.dest }}" force=no
  notify:
    - restart munin-node
  with_items:
    - {src: /usr/share/munin/plugins/sensors_, dest: sensors_fan}
    - {src: /usr/share/munin/plugins/sensors_, dest: sensors_temp}
    - {src: /usr/share/munin/plugins/sensors_, dest: sensors_volt}
  when: "{{ not 'vm' in group_names }}"
