- name: install packages
  apt: pkg={{ item }}
  with_items:
    - nginx
    - logrotate

- name: check if nginx config exists
  local_action: stat path="roles/proxycache/files/nginx-{{ inventory_hostname }}.site"
  sudo: no
  register: nginx_site

- name: copy nginx config
  copy: src=nginx-{{ inventory_hostname }}.site dest="/etc/nginx/conf.d/nginx-{{ inventory_hostname }}.conf"
  when: nginx_site.stat.exists
  notify: reload nginx

- name: generate nginx config
  template: src="nginx-site.j2" dest="/etc/nginx/sites-available/{{ item.logname }}"
    owner=root group=www-data
  with_items: "{{ proxy }}"
  when: proxy is defined
  notify: reload nginx

- name: enable nginx site
  file: src="/etc/nginx/sites-available/{{ item.logname }}" dest="/etc/nginx/sites-enabled/{{ item.logname }}" state=link
  with_items: "{{ proxy }}"
  when: proxy is defined
  notify: reload nginx
