- include: ../../../shared/project-account.yml user=letsencrypt generate_ssh_key=yes

- name: init paths
  file: path={{ item }} state=directory owner=root group=root force=no mode="0640"
  with_items:
    - /etc/ssl/letsencrypt

- name: init paths
  file: path={{ item }} state=directory owner=letsencrypt group=letsencrypt force=no mode="0700"
  with_items:
    - /data/project/letsencrypt/keys

- name: add script to download certificates
  template: src="letsencrypt-proxy.sh.j2" dest="/data/project/letsencrypt/letsencrypt-proxy.sh" owner=letsencrypt group=letsencrypt mode=0700

- name: get ssh key
  fetch: src=/data/project/letsencrypt/.ssh/id_rsa.pub dest=public_keys/ansible/letsencrypt-{{ ansible_hostname }} flat=yes

- name: init ssh key
  authorized_key: user=letsencrypt key="{{ lookup('file', inventory_dir + '/public_keys/ansible/letsencrypt-' + ansible_hostname) }}" key_options='no-pty,no-X11-forwarding,permitopen="localhost:*"'
  delegate_to: "{{ item }}"
  with_items: letsencrypt_proxy

- name: launch script
  command: /data/project/letsencrypt/letsencrypt-proxy.sh
  sudo: yes
  sudo_user: letsencrypt
  notify: reload nginx

- name: link chained.pem
  file: src="/data/project/letsencrypt/keys/{{ item }}.chained.pem" dest="/etc/ssl/letsencrypt/{{ item }}.chained.pem" state=link
  with_items: letsencrypt_proxy

- name: link domain.key
  file: src="/data/project/letsencrypt/keys/{{ item }}.domain.key" dest="/etc/ssl/letsencrypt/{{ item }}.domain.key" state=link
  with_items: letsencrypt_proxy

- name: launch script
  command: /data/project/letsencrypt/letsencrypt-proxy.sh
  sudo: yes
  sudo_user: letsencrypt
  notify: reload nginx
