- name: download proxmox apt key
  get_url:
    url: http://download.proxmox.com/debian/proxmox-ve-release-5.x.gpg
    dest: "/root/proxmox-ve-release-5.x.gpg"
    checksum: "sha512:ffb95f0f4be68d2e753c8875ea2f8465864a58431d5361e88789568673551501ae574283a4e0492f17d79dc67edfb173a56a6304dea39e01f249ebdabc9f074a"

- name: install proxmox apt key
  apt_key:
    file: "/root/proxmox-ve-release-5.x.gpg"

- name: add proxmox repository
  apt_repository:
    repo: "deb http://download.proxmox.com/debian/pmg {{ ansible_distribution_release }} pmg-no-subscription"

- name: install packages
  apt: pkg={{ item }}
  with_items:
    - proxmox-mailgateway
    - sasl2-bin
    - libsasl2-modules
