- name: install packages
  apt: pkg={{ item }}
  with_items:
    - postgresql-9.1
    - postgresql-9.1-postgis
    - postgresql-contrib-9.1
    - python-psycopg2
    - openjdk-6-jre-headless

- name: ensure postgresql server is running
  service: name=postgresql state=started

- include: ../../../shared/project-account.yml user=osmosis

- name: add sudoers to access osmosis user
  copy: src=sudoers dest=/etc/sudoers.d/osmosis-backend mode=0440 owner=root group=root validate='visudo -cf %s'

- name: init /data/work/osmosis paths
  file: path={{ item }} state=directory owner=osmosis group=osmosis
  with_items:
    - /data/work/osmosis/tmp

- name: init database
  postgresql_db: name=osm encoding='UTF-8' lc_collate='fr_FR.UTF-8' lc_ctype='fr_FR.UTF-8' template='template0'
  register: createdb_osm
  become: yes
  become_user: postgres

- name: init database user
  postgresql_user: name=osmosis password=xu4wY5KQK4 db=osm priv=ALL
  become: yes
  become_user: postgres

- name: psql extension hstore
  command: psql -d osm -c "CREATE EXTENSION IF NOT EXISTS {{ item }}"
  register: psql_res
  changed_when: "not 'extension \"{{ item }}\" already exists' in '{{ psql_res.stderr }}'"
  become: yes
  become_user: postgres
  with_items:
    - fuzzystrmatch
    - hstore

- name: psql extension postgis
  command: psql -d osm -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql
  when: createdb_osm.changed
  become: yes
  become_user: postgres

- name: psql extension postgis - spatial_ref_sys
  command: psql -d osm -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql
  when: createdb_osm.changed
  become: yes
  become_user: postgres

- name: psql access to tables
  postgresql_privs: database=osm type=table objs={{ item }} roles=osmosis privs=SELECT,INSERT,UPDATE,DELETE
  become: yes
  become_user: postgres
  with_items:
    - geometry_columns
    - spatial_ref_sys

- name: psql check schema osmosis
  command: psql -t -d osm -c "SELECT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'osmosis');"
  register: check_schema
  changed_when: "'f' in '{{ check_schema.stdout }}'"
  become: yes
  become_user: postgres

- name: psql schema osmosis
  command: psql -d osm -c "CREATE SCHEMA osmosis; ALTER USER osmosis SET search_path TO osmosis, public;"
  when: check_schema.changed
  become: yes
  become_user: osmosis

- name: psql grant access to schema osmosis to all
  postgresql_privs: database=osm type=schema objs=osmosis roles=PUBLIC privs=USAGE
  become: yes
  become_user: postgres

- name: psql grant access to tables of schema osmosis
  postgresql_privs: database=osm schema=osmosis type=table objs=ALL_IN_SCHEMA roles=PUBLIC privs=SELECT
  become: yes
  become_user: postgres

- name: checkout git repository
  git: repo=https://github.com/jocelynj/osm.git dest=/data/project/osmosis/osm force=no update=no
  become: yes
  become_user: osmosis

- name: download osmosis
  get_url: url=http://bretth.dev.openstreetmap.org/osmosis-build/osmosis-0.43.1.tgz dest=/data/project/osmosis/osmosis-0.43.1.tgz sha256sum=68df488db3643499cbc3d56fd4bd8bcabb9d67e821f9ba365b7e2eed6bda426a
  become: yes
  become_user: osmosis

- include: ../../../shared/osmosis.yml user=osmosis version=0.43.1

# To finish installation, run:
# - (cd /data/work/osmosis/ && wget http://download.openstreetmap.fr/extracts/europe/france.osm.pbf)
# - (cd osm && ./import.sh /data/work/osmosis/france.osm.pbf)
